language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: ZNV+hnaUTmRntdr1pT5D4RU4E+IMPYLqC3jG+YOqf1Ag3NuYydwMpH/8/3KqBldG8JoHWK/ppQS9y4UhH1cnh1Wtr5EM5TWLV1AjeT5IaAVl4FR2lCvMWIztCiiEfaXShYWdCBXfL1dH/wkiylct57MBVKzI+exUCT73jpKd3iX+IXVN8FvUdcvTDSWtC742xsCayM0nuUmJVBOAxHKvDNdaSmSTrxggXrhzQqL7xVTovKhvFsdzyzVAApLSbn6vX2us764x22YExlt7zMTLaqsFj+0I5udYxf7HOv8IA9u830HDjsjMnnAY/dKUXWEJpDp2COBg6LHOhdDNDCYWX9sbX9GUOoEID+4kUYTVV22fW+0RJD7Udg9YJZg1dFMTDcAL2wmH0B+Bt23BaBRQLvOG9KsPbEpO7lWv2tLfuUWwyiD5FN7VEoxpHBXJIYtTKUhYRNhDTjgzfnuDBQNiE72r6CHdYnArRw0lX1hgsrbxvzevXXPjgpnt2k0tk9F2kM3U7QhNqfXo+wuotldNPYQ26aNmUQpgzeu7QUshOYAx8pOqUymkROgGEebApXDkO4B46MwWnpGmvALVmte+Sf1lokqaNg4a0gZAR+FVe7oTkIJ3fJXhB3ER6ZsQbBnTrpl5qxzX0CHfyFs1vPm0RXlc9uCoiCSuUSpGPUJPTt8=
  app: opa-grappa
  on:
    repo: maddiereddy/OpaGrappa
