language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: U7Q3DDcuEofjDHCVvQiFhovGREFcZabEbqKkncF2pdZQkRtr5LMXGme3J7LwDWu7kGbL8o5zEfVMnssoZnTlR6QzPmLqdwZwMDrIOfcA2qPw88QxGNdAWK97451zkEUttstE4s+9KZ7iDV3G4Z2Rg9swX44V6/UsAGAyv0XvmAa2lJVlqRTKtfs0fC1wQ5viiWEIAHVdej+tkMVCoI02Ofdpsqx7wbRDQTqZE/2GGFImwlWljVH0fg7llS7F40iwWeDCYCV4mP4vWRHSx+DUo1BQt6bFp6PRlx7M7VYkHIsOGNsE2PmLAG5z2nIGWIJZF6xPNjiKXXm+V/DATMGJv6GSFzDZGDzI/FdfRbZeh5RsaqwFzz4mDPf512IcxwyjnGHsZcT2YgJeN1dBeBdk/pgQu8t7LJ+N9wZAKib9kdd8HHHRZrCJuxlsrFjM8gmq8mjQpLcLIx00BhgGohmNYqlSxla3OaWvFACFo3wfGkSXebrxTy//DScHI+P+mb2MDH0A9DyeKcP9sWhl37uVXvXhX5VSzGo9aiX6pqtAgitcuefF66lBGUkbVFmrTUgFZ47k0f1RXpOHn7/xVImzqDaCeLQv3jMg40/GFyT/jsRxJmFJFrkVHtwL/ET/WAIwIsV0pcJ3GT6RmidUtvjato0CSEYJ5U18YgJwKh35wjQ=
  app: opa-grappa
  on:
    repo: maddiereddy/OpaGrappa
